name: CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: ['Debug', 'Release']
        platform: ['x64']
        triplet: ['x64-windows']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Checkout QtMsBuild
      uses: actions/checkout@v4
      with:
        repository: Cortana4/QtMsBuild
        path: ./QtMsBuild

    #- name: Checkout Qt vstools
    #  uses: actions/checkout@v4
    #  with:
    #    repository: qt-labs/vstools
    #    path: ${{ github.workspace }}/vstools

    #- name: Set QtMsBuild Environment Variable
    #  run: echo "QtMsBuild=${{ github.workspace }}/vstools/QtMSBuild/QtMsBuild" >> $env:GITHUB_ENV

    - name: Checkout vcpkg
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        path: ./vcpkg
    
    - name: Setup vcpkg
      run: |
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg integrate install

    #- name: Setup vcpkg
    #  uses: lukka/run-vcpkg@v11
    #  with:
    #    #vcpkgGitCommitId: 6f1ddd6b6878e7e66fcc35c65ba1d8feec2e01f8
    #    vcpkgDirectory: ${{ github.workspace }}/vcpkg
    #    doNotCache: true
    #    runVcpkgInstall: true

    #- name: Run vcpkg integrate install
    #  run: ./vcpkg/vcpkg integrate install

    #- name: Checkout vcpkg
    #  uses: actions/checkout@v4
    #  with:
    #    repository: microsoft/vcpkg
    #    path: vcpkg


    - name: Invoke Developer Command Prompt for VS
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Dependencies
      run: vcpkg install --x-wait-for-lock --triplet ${{ matrix.triplet }} --x-install-root=vcpkg_installed

    - name: Build
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.platform }}-${{ matrix.configuration }}
        path: bin/${{ matrix.platform == 'x86' && 'Win32' || matrix.platform }}/${{ matrix.configuration }}
